In [4]:
import numpy as np
import pandas as pd

In [8]:
d1={'name':['Ram','Shyam','Sita'],
   'scores':[90,80,70]}
df1=pd.DataFrame(d1)
df1

    name  scores
0    Ram      90
1  Shyam      80
2   Sita      70

In [6]:
d={'name':['B','M'],
  'scores':[70,85]}
df2=pd.DataFrame(d)
df2

  name  scores
0    B      70
1    M      85

In [10]:
pd.concat([df1, df2])

    name  scores
0    Ram      90
1  Shyam      80
2   Sita      70
0      B      70
1      M      85

In [20]:
t=pd.concat([df1, df2], ignore_index=True)
t

    name  scores
0    Ram      90
1  Shyam      80
2   Sita      70
3      B      70
4      M      85

In [14]:
df3=pd.DataFrame({'age':[23,25,27,22,30]})
df3

   age
0   23
1   25
2   27
3   22
4   30

In [24]:
df=pd.concat([t,df3],axis=1)
df

    name  scores  age
0    Ram      90   23
1  Shyam      80   25
2   Sita      70   27
3      B      70   22
4      M      85   30

In [28]:
df.replace(23,25)

    name  scores  age
0    Ram      90   25
1  Shyam      80   25
2   Sita      70   27
3      B      70   22
4      M      85   30

In [32]:
df['age'].replace([23,27],[25,40])

0    25
1    25
2    40
3    22
4    30
Name: age, dtype: int64

In [42]:
df['age'].replace({23:29,27:40})

0    29
1    25
2    40
3    22
4    30
Name: age, dtype: int64