In [1]:
"""
what is a series? 
Series is a 1D labeled array built on Numpy ndarray 
main components of series : indices, values (index-labels: customised indexing)
2D : DataFrame : when we merge two or more series we get a dataframe
each column is a series and each row is a series
table inside python is a dataframe
"""

'\nwhat is a series? \nSeries is a 1D labeled array built on Numpy ndarray \nmain components of series : indices, values (index-labels: customised indexing)\n2D : DataFrame : when we merge two or more series we get a dataframe\neach column is a series and each row is a series\ntable inside python is a dataframe\n'

In [2]:
import numpy as np
import pandas as pd

In [3]:
ser1 = pd.Series(['Sania', 'Simran', 'Rumela', 'Ritika'])
ser2 = pd.Series([80, 78, 96, 68])
df = pd.DataFrame([ser1, ser2])
df

       0       1       2       3
0  Sania  Simran  Rumela  Ritika
1     80      78      96      68

In [4]:
df=pd.DataFrame({'name':ser1, 'score':ser2})
df

     name  score
0   Sania     80
1  Simran     78
2  Rumela     96
3  Ritika     68

In [5]:
l=[
    ['Sania', 80],
    ['Simran', 78],
    ['Rumela', 96],
    ['Ritika', 68]
]
dfl=pd.DataFrame(l, columns=['name', 'score'],index=['a','b','c','d'])
dfl.loc['c':'a':-1,:]     #loc includes the last index

     name  score
c  Rumela     96
b  Simran     78
a   Sania     80

In [6]:
dfl.iloc[0:3,:]

     name  score
a   Sania     80
b  Simran     78
c  Rumela     96

In [7]:
l=[
    ['Sania', 80],
    ['Simran', 78],
    ['Rumela', 96],
    ['Ritika', 68]
]
dfl=pd.DataFrame(l)
dfl

        0   1
0   Sania  80
1  Simran  78
2  Rumela  96
3  Ritika  68

In [8]:
d={
    'name':['Sania','Simran','Rumela','Ritika'],
    'score':[80, 78, 96, 68]
}
dfd=pd.DataFrame(d)
dfd

     name  score
0   Sania     80
1  Simran     78
2  Rumela     96
3  Ritika     68

In [9]:
data=pd.read_csv('winemag-data-130k-v2.csv')
data

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [10]:
datam=pd.read_csv('winemag-data-130k-v2.csv', index_col=0)
datam

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [11]:
datam.shape

(129971, 13)

In [12]:
datam.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

In [13]:
datam.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [14]:
num_df = datam.select_dtypes(include='number')
num_df.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [15]:
non_num_df = datam.select_dtypes(include='object')
non_num_df.describe()

,country,description,designation,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,129908,129971,92506,129908,108724,50511,103727,98758,129971,129970,129971
unique,43,119955,37979,425,1229,17,19,15,118840,707,16757
top,US,"Seductively tart in lemon pith, cranberry and ...",Reserve,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Wines & Winemakers
freq,54504,3,2009,36247,4480,11065,25514,25514,11,13272,222

In [16]:
datam[['country','title','price']]

         country                                              title  price
0          Italy                  Nicosia 2013 Vulkà Bianco  (Etna)    NaN
1       Portugal      Quinta dos Avidagos 2011 Avidagos Red (Douro)   15.0
2             US      Rainstorm 2013 Pinot Gris (Willamette Valley)   14.0
3             US  St. Julian 2013 Reserve Late Harvest Riesling ...   13.0
4             US  Sweet Cheeks 2012 Vintner's Reserve Wild Child...   65.0
...          ...                                                ...    ...
129966   Germany  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...   28.0
129967        US                  Citation 2004 Pinot Noir (Oregon)   75.0
129968    France  Domaine Gresser 2013 Kritt Gewurztraminer (Als...   30.0
129969    France      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)   32.0
129970    France  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...   21.0

[129971 rows x 3 columns]

In [17]:
datam['country'].values

array(['Italy', 'Portugal', 'US', ..., 'France', 'France', 'France'],
      dtype=object)

In [18]:
datam.index

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

In [19]:
datam.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [20]:
datam['country'].value_counts(ascending=True)

country
Egypt                         1
Slovakia                      1
China                         1
Bosnia and Herzegovina        2
Armenia                       2
Luxembourg                    6
Switzerland                   7
India                         9
Cyprus                       11
Macedonia                    12
Serbia                       12
Czech Republic               12
Ukraine                      14
Peru                         16
Morocco                      28
Lebanon                      35
Brazil                       52
Moldova                      59
Mexico                       70
Croatia                      73
England                      74
Georgia                      86
Slovenia                     87
Turkey                       90
Uruguay                     109
Romania                     120
Bulgaria                    141
Hungary                     146
Canada                      257
Greece                      466
Israel                      505
South Africa               1401
New Zealand                1419
Germany                    2165
Australia                  2329
Austria                    3345
Argentina                  3800
Chile                      4472
Portugal                   5691
Spain                      6645
Italy                     19540
France                    22093
US                        54504
Name: count, dtype: int64

In [21]:
datam['country'].value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [22]:
datam['points'].value_counts(ascending=True)

points
100       19
99        33
98        77
97       229
80       397
96       523
81       692
95      1535
82      1836
83      3025
94      3758
84      6480
93      6489
85      9530
92      9613
91     11359
89     12226
86     12600
90     15410
87     16933
88     17207
Name: count, dtype: int64

In [23]:
datar=datam.rename(columns={'country':'Country', 'points':'Points', 'description':'Description','designation':'Designation'
                     ,'price':'Price', 'province':'Province', 'region_1':'Region_1','region_2':'Region_2',
                     'taster_name': 'Taster_Name', 'taster_twitter_handle':'Taster_Twitter_Handle','title':'Title',
                     'variety':'Variety', 'winery':'Winery'})
datar

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [24]:
#datar.iloc[rows,columns]
datar.iloc[:1000,2:]

,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...
995,Edèlmio,88,26.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Benanti 2006 Edèlmio White (Sicilia),White Blend,Benanti
996,Terre di Giumara,88,14.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Caruso & Minini 2006 Terre di Giumara Syrah (S...,Syrah,Caruso & Minini
997,Patchwork,88,18.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Yalumba 2006 Patchwork Shiraz (Barossa),Shiraz,Yalumba
998,NaN,88,18.0,Oregon,Dundee Hills,Willamette Valley,Paul Gregutt,@paulgwine,The Four Graces 2007 Pinot Gris (Dundee Hills),Pinot Gris,The Four Graces
999,NaN,88,17.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Amity 2006 Riesling (Willamette Valley),Riesling,Amity

In [25]:
datar.iloc[:1000,2::2]

,Designation,Price,Region_1,Taster_Name,Title,Winery
0,Vulkà Bianco,NaN,Etna,Kerin O’Keefe,Nicosia 2013 Vulkà Bianco (Etna),Nicosia
1,Avidagos,15.0,NaN,Roger Voss,Quinta dos Avidagos 2011 Avidagos Red (Douro),Quinta dos Avidagos
2,NaN,14.0,Willamette Valley,Paul Gregutt,Rainstorm 2013 Pinot Gris (Willamette Valley),Rainstorm
3,Reserve Late Harvest,13.0,Lake Michigan Shore,Alexander Peartree,St. Julian 2013 Reserve Late Harvest Riesling ...,St. Julian
4,Vintner's Reserve Wild Child Block,65.0,Willamette Valley,Paul Gregutt,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Sweet Cheeks
...,...,...,...,...,...,...
995,Edèlmio,26.0,Sicilia,NaN,Benanti 2006 Edèlmio White (Sicilia),Benanti
996,Terre di Giumara,14.0,Sicilia,NaN,Caruso & Minini 2006 Terre di Giumara Syrah (S...,Caruso & Minini
997,Patchwork,18.0,Barossa,Joe Czerwinski,Yalumba 2006 Patchwork Shiraz (Barossa),Yalumba
998,NaN,18.0,Dundee Hills,Paul Gregutt,The Four Graces 2007 Pinot Gris (Dundee Hills),The Four Graces
999,NaN,17.0,Willamette Valley,Paul Gregutt,Amity 2006 Riesling (Willamette Valley),Amity

In [26]:
datar.iloc[30000::-2,::2]          #iloc doesnot include last index

,Country,Designation,Price,Region_1,Taster_Name,Title,Winery
30000,Austria,Ried Grillenparz Reserve,40.0,NaN,Anne Krebiehl MW,Stadt Krems 2014 Ried Grillenparz Reserve Ries...,Stadt Krems
29998,US,High Elevation Collection,23.0,Lake County,Jim Gordon,Shannon Ridge 2013 High Elevation Collection P...,Shannon Ridge
29996,US,No. 198 Single Vineyard Reserve,19.0,Finger Lakes,Anna Lee C. Iijima,Boundary Breaks 2013 No. 198 Single Vineyard R...,Boundary Breaks
29994,France,Blue Label Brut,36.0,Champagne,Roger Voss,Nicolas Feuillatte NV Blue Label Brut (Champa...,Nicolas Feuillatte
29992,Greece,NaN,21.0,NaN,Susan Kostrzewa,Mediterra 2007 Vilana (Crete),Mediterra
...,...,...,...,...,...,...,...
8,Germany,Shine,12.0,NaN,Anna Lee C. Iijima,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Heinz Eifel
6,Italy,Belsito,16.0,Vittoria,Kerin O’Keefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Terre di Giurfo
4,US,Vintner's Reserve Wild Child Block,65.0,Willamette Valley,Paul Gregutt,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Sweet Cheeks
2,US,NaN,14.0,Willamette Valley,Paul Gregutt,Rainstorm 2013 Pinot Gris (Willamette Valley),Rainstorm
0,Italy,Vulkà Bianco,NaN,Etna,Kerin O’Keefe,Nicosia 2013 Vulkà Bianco (Etna),Nicosia

In [27]:
datar.isnull().sum(axis=0)

Country                     63
Description                  0
Designation              37465
Points                       0
Price                     8996
Province                    63
Region_1                 21247
Region_2                 79460
Taster_Name              26244
Taster_Twitter_Handle    31213
Title                        0
Variety                      1
Winery                       0
dtype: int64

In [28]:
datar.isnull()

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,False,False,False,False,False,False,True,True,False,True,False,False,False
129967,False,False,True,False,False,False,False,False,False,False,False,False,False
129968,False,False,False,False,False,False,False,True,False,False,False,False,False
129969,False,False,True,False,False,False,False,True,False,False,False,False,False
129970,False,False,False,False,False,False,False,True,False,False,False,False,False

In [29]:
datar.dropna()

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
23,US,This wine from the Geneseo district offers aro...,Signature Selection,87,22.0,California,Paso Robles,Central Coast,Matt Kettmann,@mattkettmann,Bianchi 2011 Signature Selection Merlot (Paso ...,Merlot,Bianchi
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley,Paul Gregutt,@paulgwine,Erath 2010 Hyland Pinot Noir (McMinnville),Pinot Noir,Erath
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129919,US,"This ripe, rich, almost decadently thick wine ...",Reserve,91,105.0,Washington,Walla Walla Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Nicholas Cole Cellars 2004 Reserve Red (Walla ...,Red Blend,Nicholas Cole Cellars
129926,US,This pure Syrah from Reininger's estate vineya...,Ash Hollow Vineyard,91,41.0,Washington,Walla Walla Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Reininger 2005 Ash Hollow Vineyard Syrah (Wall...,Syrah,Reininger
129945,US,Hailing from one of the more popular vineyards...,Jurassic Park Vineyard Old Vines,90,20.0,California,Santa Ynez Valley,Central Coast,Matt Kettmann,@mattkettmann,Birichino 2013 Jurassic Park Vineyard Old Vine...,Chenin Blanc,Birichino
129949,US,There's no bones about the use of oak in this ...,Barrel Fermented,90,35.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Flora Springs 2013 Barrel Fermented Chardonnay...,Chardonnay,Flora Springs
129950,US,This opens with herbaceous dollops of thyme an...,Blocks 7 & 22,90,35.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley),Zinfandel,Hendry

In [30]:
datar.isnull()

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,False,False,False,False,False,False,True,True,False,True,False,False,False
129967,False,False,True,False,False,False,False,False,False,False,False,False,False
129968,False,False,False,False,False,False,False,True,False,False,False,False,False
129969,False,False,True,False,False,False,False,True,False,False,False,False,False
129970,False,False,False,False,False,False,False,True,False,False,False,False,False

In [31]:
datar_1=datar[:40000]
datar_1.isnull().sum()

Country                     18
Description                  0
Designation              11422
Points                       0
Price                     2881
Province                    18
Region_1                  6625
Region_2                 24606
Taster_Name               8189
Taster_Twitter_Handle     9686
Title                        0
Variety                      0
Winery                       0
dtype: int64

In [32]:
datar_1.dropna()

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
23,US,This wine from the Geneseo district offers aro...,Signature Selection,87,22.0,California,Paso Robles,Central Coast,Matt Kettmann,@mattkettmann,Bianchi 2011 Signature Selection Merlot (Paso ...,Merlot,Bianchi
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley,Paul Gregutt,@paulgwine,Erath 2010 Hyland Pinot Noir (McMinnville),Pinot Noir,Erath
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39976,US,"This wine is a solid, stylish Meritage with as...",Red Table Wine,84,25.0,New York,Finger Lakes,Finger Lakes,Susan Kostrzewa,@suskostrzewa,Atwater 2005 Red Table Wine Meritage (Finger L...,Meritage,Atwater
39981,US,This lush white starts with a nose of apricot ...,Ravat 51,84,7.0,New York,New York,New York Other,Susan Kostrzewa,@suskostrzewa,Bully Hill NV Ravat 51 White (New York),White Blend,Bully Hill
39988,US,Cherry and mocha on the nose start this wine n...,Keuka Hill Reserve Red Table Wine,84,23.0,New York,Finger Lakes,Finger Lakes,Susan Kostrzewa,@suskostrzewa,Shaw NV Keuka Hill Reserve Red Table Wine Red ...,Bordeaux-style Red Blend,Shaw
39992,US,How's this for exotic: this red blend is made ...,Black Russian Red,84,60.0,New York,Finger Lakes,Finger Lakes,Susan Kostrzewa,@suskostrzewa,McGregor 2005 Black Russian Red Red (Finger La...,Red Blend,McGregor
39999,US,"Earthy, mature, beefy flavors lend an unorthod...",Love Ranch Vineyard,87,31.0,California,Madera,Central Valley,Jim Gordon,@gordone_cellars,Dante Robere 2013 Love Ranch Vineyard Mourvèdr...,Mourvèdre,Dante Robere

In [33]:
datar_1.dropna().sum()

Country                  USUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUS...
Description              Much like the regular bottling from 2012, this...
Designation              Vintner's Reserve Wild Child BlockMountain Cuv...
Points                                                              607953
Price                                                             281933.0
Province                 OregonCaliforniaCaliforniaCaliforniaOregonCali...
Region_1                 Willamette ValleyNapa ValleyPaso RoblesSonoma ...
Region_2                 Willamette ValleyNapaCentral CoastSonomaWillam...
Taster_Name              Paul GreguttVirginie BooneMatt KettmannVirgini...
Taster_Twitter_Handle    @paulgwine @vboone@mattkettmann@vboone@paulgwi...
Title                    Sweet Cheeks 2012 Vintner's Reserve Wild Child...
Variety                  Pinot NoirCabernet SauvignonMerlotPinot NoirPi...
Winery                   Sweet CheeksKirkland SignatureBianchiCastello ...
dtype: object

In [34]:
datar_1.dropna().shape

(6790, 13)

In [35]:
temp=datar_1.dropna()
temp.isnull().sum()

Country                  0
Description              0
Designation              0
Points                   0
Price                    0
Province                 0
Region_1                 0
Region_2                 0
Taster_Name              0
Taster_Twitter_Handle    0
Title                    0
Variety                  0
Winery                   0
dtype: int64

In [36]:
datar_1.shape

(40000, 13)

In [37]:
temp.shape

(6790, 13)

In [38]:
datar_1.dropna(subset=['Designation','Province'], how='any').shape      #any: AND   all:OR   deafult:any

(28564, 13)

In [39]:
datar.fillna('not available')

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,not available,Sicily & Sardinia,Etna,not available,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,not available,not available,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",not available,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,not available,Alexander Peartree,not available,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,not available,not available,Anna Lee C. Iijima,not available,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,not available,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,not available,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",not available,90,32.0,Alsace,Alsace,not available,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,not available,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [40]:
datar_1.duplicated().sum()

926

In [41]:
datar_1[datar_1.duplicated()]

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
2408,US,"This is weighty, creamy and medium to full in ...",NaN,85,14.0,California,North Coast,North Coast,Virginie Boone,@vboone,Souverain 2010 Chardonnay (North Coast),Chardonnay,Souverain
2409,Italy,There's a touch of toasted almond at the start...,Sallier de la Tour,85,13.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Tasca d'Almerita 2011 Sallier de la Tour Grill...,Grillo,Tasca d'Almerita
2410,Chile,Lightly herbal strawberry and raspberry aromas...,Reserve,85,13.0,Maipo Valley,NaN,NaN,Michael Schachner,@wineschach,Tres Palacios 2011 Reserve Pinot Noir (Maipo V...,Pinot Noir,Tres Palacios
2412,Italy,The Monica grape often shows a rustic or raw q...,Dolia,85,14.0,Sicily & Sardinia,Monica di Sardegna,NaN,NaN,NaN,Cantine di Dolianova 2010 Dolia (Monica di Sa...,Monica,Cantine di Dolianova
2413,France,"Fruity and lightly herbaceous, this has fine t...",La Fleur d'Amélie,85,15.0,Bordeaux,Bordeaux Blanc,NaN,Roger Voss,@vossroger,Château de Sours 2011 La Fleur d'Amélie (Bord...,Bordeaux-style White Blend,Château de Sours
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39854,France,This is a nutty wine with flavors of hazelnuts...,Brut,87,NaN,Loire Valley,Vouvray,NaN,Roger Voss,@vossroger,Domaine de Vaugondy NV Brut (Vouvray),Chenin Blanc,Domaine de Vaugondy
39855,France,This wine reflects the ripeness of the vintage...,NaN,87,25.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Vrignaud 2015 Chablis,Chardonnay,Domaine Vrignaud
39856,France,This is an attractive red-fruit flavored wine ...,Domaine de la Ferté,87,35.0,Burgundy,Givry,NaN,Roger Voss,@vossroger,Domaines Devillard 2014 Domaine de la Ferté (...,Pinot Noir,Domaines Devillard
39857,France,"Showing the ripe 2015 vintage, this is a soft ...",NaN,87,25.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Etienne Boileau 2015 Chablis,Chardonnay,Etienne Boileau
39956,France,"This is very light, in both flavor and body. T...",NaN,81,17.0,Bordeaux,Bordeaux,NaN,Joe Czerwinski,@JoeCz,Château Maine-Gazin 1997 Bordeaux,Bordeaux-style Red Blend,Château Maine-Gazin

In [42]:
datar_1[datar_1.duplicated(keep=False)].shape    #keep duplicate values

(1852, 13)

In [43]:
datar_1[datar_1.duplicated(keep='last')].shape    #each value as 2 occurances as infered

(926, 13)

In [44]:
datar_1.drop_duplicates(subset=['Designation','Province'])

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39985,US,"Lemon citrus, toast, white flowers—the lead on...",Spring Wine,84,13.0,Pennsylvania,Pennsylvania,NaN,Susan Kostrzewa,@suskostrzewa,Chaddsford 2007 Spring Wine White (Pennsylvania),White Blend,Chaddsford
39987,Spain,"Quite tannic and biting, but beyond those mout...",Monte Castrillo,84,13.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Finca Torremilanos 2006 Monte Castrillo (Ribe...,Tempranillo Blend,Finca Torremilanos
39988,US,Cherry and mocha on the nose start this wine n...,Keuka Hill Reserve Red Table Wine,84,23.0,New York,Finger Lakes,Finger Lakes,Susan Kostrzewa,@suskostrzewa,Shaw NV Keuka Hill Reserve Red Table Wine Red ...,Bordeaux-style Red Blend,Shaw
39992,US,How's this for exotic: this red blend is made ...,Black Russian Red,84,60.0,New York,Finger Lakes,Finger Lakes,Susan Kostrzewa,@suskostrzewa,McGregor 2005 Black Russian Red Red (Finger La...,Red Blend,McGregor
39994,Italy,A blend of Tintore and Per'e Palummo (a grape ...,Costa d'Amalfi Tramonti,84,18.0,Southern Italy,Campania,NaN,NaN,NaN,Giuseppe Apicella 2006 Costa d'Amalfi Tramonti...,Red Blend,Giuseppe Apicella

In [45]:
datar_1.drop_duplicates(subset=['Designation','Province']).shape

(18475, 13)

In [46]:
datar_1.drop_duplicates(subset=['Designation','Province'], keep=False).shape

(14143, 13)

In [47]:
datar_1['Country'].value_counts(ascending=True)

Country
Bosnia and Herzegovina        1
Armenia                       1
Luxembourg                    1
Slovakia                      1
Switzerland                   3
India                         3
Macedonia                     4
Ukraine                       4
Cyprus                        4
Morocco                       5
Serbia                        5
Czech Republic                5
Peru                          6
Lebanon                      11
England                      12
Moldova                      17
Slovenia                     19
Turkey                       22
Mexico                       22
Brazil                       23
Georgia                      24
Croatia                      29
Hungary                      35
Romania                      39
Bulgaria                     41
Uruguay                      42
Canada                       76
Greece                      140
Israel                      161
South Africa                453
New Zealand                 466
Germany                     666
Australia                   703
Austria                    1038
Argentina                  1187
Chile                      1398
Portugal                   1784
Spain                      2043
Italy                      6144
France                     6766
US                        16578
Name: count, dtype: int64

In [48]:
datar_1['Country'].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia'],
      dtype=object)

In [49]:
datar_1['Country'].unique().size

42

In [50]:
datar_1['Country'].isnull().sum()

18

In [51]:
datar_1['Country'].nunique()         #doesnot consider nan values

41

In [52]:
datar_1.sort_values(by=['Country'], ascending=False).head()

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
38811,Uruguay,Ignore the crazy price on this aged Tannat and...,1st Cru d'Exception,88,120.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2006 1st Cru d'Exception Tannat...,Tannat,Familia Deicas
4051,Uruguay,Ripe earthy aromas of raisin and oaky vanilla ...,B2 Parcela Unica,88,43.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Bouza 2013 B2 Parcela Unica Tannat (Canelones),Tannat,Bouza
14722,Uruguay,Hard cherry and nail polish aromas rise up fro...,Don Pascual Reserve,82,12.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2008 Don Pascual Reserve Tannat...,Tannat,Familia Deicas
37960,Uruguay,"Lightweight, almost dilute aromas of pool wate...",Varietales,85,17.0,Uruguay,NaN,NaN,Michael Schachner,@wineschach,Garzón 2014 Varietales Albariño (Uruguay),Albariño,Garzón
12719,Uruguay,Bouza continues to lead the Uruguayan charge v...,Reserva,88,19.0,Montevideo,NaN,NaN,Michael Schachner,@wineschach,Bouza 2013 Reserva Tannat (Montevideo),Tannat,Bouza

In [53]:
datar_1.sort_index()

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,Spain,"Red in color and pretty clean on the nose, whe...",Rosado,84,8.0,Northern Spain,Campo de Borja,NaN,Michael Schachner,@wineschach,Coto de Hayas 2007 Rosado Rosé (Campo de Borja),Rosé,Coto de Hayas
39996,Italy,The nose here is very sweet and ripe and recal...,NaN,84,20.0,Southern Italy,Lacryma Christi del Vesuvio,NaN,NaN,NaN,Digi Or NV Coda di Volpe (Lacryma Christi del ...,Coda di Volpe,Digi Or
39997,US,Honey and toasted spice aromas are followed by...,NaN,84,20.0,Arizona,Cochise County,NaN,Susan Kostrzewa,@suskostrzewa,Dos Cabezas 2006 Viognier (Cochise County),Viognier,Dos Cabezas
39998,US,"The winery is in eastern Oregon, near the Idah...",NaN,87,28.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Copper Belt 2013 Pinot Noir (Willamette Valley),Pinot Noir,Copper Belt
39999,US,"Earthy, mature, beefy flavors lend an unorthod...",Love Ranch Vineyard,87,31.0,California,Madera,Central Valley,Jim Gordon,@gordone_cellars,Dante Robere 2013 Love Ranch Vineyard Mourvèdr...,Mourvèdre,Dante Robere

In [54]:
datar_1.drop(columns=['Region_2','Region_1'])

,Country,Description,Designation,Points,Price,Province,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...
39995,Spain,"Red in color and pretty clean on the nose, whe...",Rosado,84,8.0,Northern Spain,Michael Schachner,@wineschach,Coto de Hayas 2007 Rosado Rosé (Campo de Borja),Rosé,Coto de Hayas
39996,Italy,The nose here is very sweet and ripe and recal...,NaN,84,20.0,Southern Italy,NaN,NaN,Digi Or NV Coda di Volpe (Lacryma Christi del ...,Coda di Volpe,Digi Or
39997,US,Honey and toasted spice aromas are followed by...,NaN,84,20.0,Arizona,Susan Kostrzewa,@suskostrzewa,Dos Cabezas 2006 Viognier (Cochise County),Viognier,Dos Cabezas
39998,US,"The winery is in eastern Oregon, near the Idah...",NaN,87,28.0,Oregon,Paul Gregutt,@paulgwine,Copper Belt 2013 Pinot Noir (Willamette Valley),Pinot Noir,Copper Belt
39999,US,"Earthy, mature, beefy flavors lend an unorthod...",Love Ranch Vineyard,87,31.0,California,Jim Gordon,@gordone_cellars,Dante Robere 2013 Love Ranch Vineyard Mourvèdr...,Mourvèdre,Dante Robere

In [55]:
t2=datar_1.set_index('Country')
t2.reset_index(inplace=True)
t2.set_index('Title')

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Variety,Winery
Title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...
Coto de Hayas 2007 Rosado Rosé (Campo de Borja),Spain,"Red in color and pretty clean on the nose, whe...",Rosado,84,8.0,Northern Spain,Campo de Borja,NaN,Michael Schachner,@wineschach,Rosé,Coto de Hayas
Digi Or NV Coda di Volpe (Lacryma Christi del Vesuvio),Italy,The nose here is very sweet and ripe and recal...,NaN,84,20.0,Southern Italy,Lacryma Christi del Vesuvio,NaN,NaN,NaN,Coda di Volpe,Digi Or
Dos Cabezas 2006 Viognier (Cochise County),US,Honey and toasted spice aromas are followed by...,NaN,84,20.0,Arizona,Cochise County,NaN,Susan Kostrzewa,@suskostrzewa,Viognier,Dos Cabezas
Copper Belt 2013 Pinot Noir (Willamette Valley),US,"The winery is in eastern Oregon, near the Idah...",NaN,87,28.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Copper Belt
Dante Robere 2013 Love Ranch Vineyard Mourvèdre (Madera),US,"Earthy, mature, beefy flavors lend an unorthod...",Love Ranch Vineyard,87,31.0,California,Madera,Central Valley,Jim Gordon,@gordone_cellars,Mourvèdre,Dante Robere

In [56]:
datar.reset_index(drop=True)

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [57]:
datar_1[(datar_1['Points']>90) & ((datar_1['Country']=='France') | (datar_1['Country']=='Italy'))]

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
119,France,Medium-gold in color. Complex and inviting nos...,Schoenenbourg Grand Cru Vendanges Tardives,92,80.0,Alsace,Alsace,NaN,NaN,NaN,Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...,Riesling,Dopff & Irion
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
126,France,Mid-gold color. Pronounced and enticing aromas...,Vendages Tardives,91,48.0,Alsace,Alsace,NaN,NaN,NaN,Pierre Sparr 2007 Vendages Tardives Gewurztram...,Gewürztraminer,Pierre Sparr
127,France,Attractive mid-gold color with intense aromas ...,Alsace One,91,13.0,Alsace,Alsace,NaN,NaN,NaN,Pierre Sparr 2008 Alsace One White (Alsace),White Blend,Pierre Sparr
128,France,"Compelling minerality on the nose, Refined and...",NaN,91,17.0,Alsace,Alsace,NaN,NaN,NaN,Kuentz-Bas 2008 Pinot Blanc (Alsace),Pinot Blanc,Kuentz-Bas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39692,France,"This is a full-bodied, dense wine. A hint of a...",Montmains Premier Cru,93,38.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Jean-Paul et Benoît Droin 2013 Montmai...,Chardonnay,Domaine Jean-Paul et Benoît Droin
39693,France,"Floral and aromatic, this is a ripe wine with ...",Les Vaucoupins Premier Cru,93,NaN,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Laroche 2012 Les Vaucoupins Premier Cr...,Chardonnay,Domaine Laroche
39808,France,"Pale pink in color, this is a full, fruity win...",Tsarine Millésime Brut Rosé,91,75.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Chanoine 2005 Tsarine Millésime Brut Rosé (Ch...,Champagne Blend,Chanoine
39809,Italy,Tremenel has an earthy fragrance of underbrush...,Tremenel,91,65.0,Veneto,Amarone della Valpolicella,NaN,Kerin O’Keefe,@kerinokeefe,Villa Erbice 2007 Tremenel (Amarone della Val...,Red Blend,Villa Erbice
39965,France,A voluptuous blockbuster in the style we are b...,Le Pigeonnier,93,60.0,Southwest France,Cahors,NaN,Joe Czerwinski,@JoeCz,Château Lagrézette 1997 Le Pigeonnier Malbec (...,Malbec,Château Lagrézette

In [58]:
datar_1[(datar_1['Points']>90) & (datar_1['Country'].isin(['France', 'Italy']))]

,Country,Description,Designation,Points,Price,Province,Region_1,Region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
119,France,Medium-gold in color. Complex and inviting nos...,Schoenenbourg Grand Cru Vendanges Tardives,92,80.0,Alsace,Alsace,NaN,NaN,NaN,Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...,Riesling,Dopff & Irion
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
126,France,Mid-gold color. Pronounced and enticing aromas...,Vendages Tardives,91,48.0,Alsace,Alsace,NaN,NaN,NaN,Pierre Sparr 2007 Vendages Tardives Gewurztram...,Gewürztraminer,Pierre Sparr
127,France,Attractive mid-gold color with intense aromas ...,Alsace One,91,13.0,Alsace,Alsace,NaN,NaN,NaN,Pierre Sparr 2008 Alsace One White (Alsace),White Blend,Pierre Sparr
128,France,"Compelling minerality on the nose, Refined and...",NaN,91,17.0,Alsace,Alsace,NaN,NaN,NaN,Kuentz-Bas 2008 Pinot Blanc (Alsace),Pinot Blanc,Kuentz-Bas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39692,France,"This is a full-bodied, dense wine. A hint of a...",Montmains Premier Cru,93,38.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Jean-Paul et Benoît Droin 2013 Montmai...,Chardonnay,Domaine Jean-Paul et Benoît Droin
39693,France,"Floral and aromatic, this is a ripe wine with ...",Les Vaucoupins Premier Cru,93,NaN,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Laroche 2012 Les Vaucoupins Premier Cr...,Chardonnay,Domaine Laroche
39808,France,"Pale pink in color, this is a full, fruity win...",Tsarine Millésime Brut Rosé,91,75.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Chanoine 2005 Tsarine Millésime Brut Rosé (Ch...,Champagne Blend,Chanoine
39809,Italy,Tremenel has an earthy fragrance of underbrush...,Tremenel,91,65.0,Veneto,Amarone della Valpolicella,NaN,Kerin O’Keefe,@kerinokeefe,Villa Erbice 2007 Tremenel (Amarone della Val...,Red Blend,Villa Erbice
39965,France,A voluptuous blockbuster in the style we are b...,Le Pigeonnier,93,60.0,Southwest France,Cahors,NaN,Joe Czerwinski,@JoeCz,Château Lagrézette 1997 Le Pigeonnier Malbec (...,Malbec,Château Lagrézette

In [59]:
def test_func(row):
    return str(row[0])+' '+str(row[5])
datar['new_col']=datar.apply(test_func, axis=1)
datar['new_col']

C:\Users\shama\AppData\Local\Temp\ipykernel_19116\1887610127.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return str(row[0])+' '+str(row[5])

0         Italy Sicily & Sardinia
1                  Portugal Douro
2                       US Oregon
3                     US Michigan
4                       US Oregon
                   ...
129966              Germany Mosel
129967                  US Oregon
129968              France Alsace
129969              France Alsace
129970              France Alsace
Name: new_col, Length: 129971, dtype: object

In [60]:
datar['new_col']

0         Italy Sicily & Sardinia
1                  Portugal Douro
2                       US Oregon
3                     US Michigan
4                       US Oregon
                   ...
129966              Germany Mosel
129967                  US Oregon
129968              France Alsace
129969              France Alsace
129970              France Alsace
Name: new_col, Length: 129971, dtype: object