In [ ]:
"""
what is a series? 
Series is a 1D labeled array built on Numpy ndarray 
main components of series : indices, values (index-labels: customised indexing)
2D : DataFrame : when we merge two or more series we get a dataframe
each column is a series and each row is a series
table inside python is a dataframe
"""

In [3]:
import numpy as np
import pandas as pd

In [5]:
ser1 = pd.Series(['Sania', 'Simran', 'Rumela', 'Ritika'])
ser2 = pd.Series([80, 78, 96, 68])
df = pd.DataFrame([ser1, ser2])
df

       0       1       2       3
0  Sania  Simran  Rumela  Ritika
1     80      78      96      68

In [7]:
df=pd.DataFrame({'name':ser1, 'score':ser2})
df

     name  score
0   Sania     80
1  Simran     78
2  Rumela     96
3  Ritika     68

In [105]:
l=[
    ['Sania', 80],
    ['Simran', 78],
    ['Rumela', 96],
    ['Ritika', 68]
]
dfl=pd.DataFrame(l, columns=['name', 'score'],index=['a','b','c','d'])
dfl.loc['c':'a':-1,:]     #loc includes the last index

     name  score
c  Rumela     96
b  Simran     78
a   Sania     80

In [109]:
dfl.iloc[0:3,:]

     name  score
a   Sania     80
b  Simran     78
c  Rumela     96

In [11]:
l=[
    ['Sania', 80],
    ['Simran', 78],
    ['Rumela', 96],
    ['Ritika', 68]
]
dfl=pd.DataFrame(l)
dfl

        0   1
0   Sania  80
1  Simran  78
2  Rumela  96
3  Ritika  68

In [13]:
d={
    'name':['Sania','Simran','Rumela','Ritika'],
    'score':[80, 78, 96, 68]
}
dfd=pd.DataFrame(d)
dfd

     name  score
0   Sania     80
1  Simran     78
2  Rumela     96
3  Ritika     68

In [19]:
data=pd.read_csv('winemag-data-130k-v2.csv')
data

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [21]:
datam=pd.read_csv('winemag-data-130k-v2.csv', index_col=0)
datam

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [23]:
datam.shape

(129971, 13)

In [27]:
datam.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

In [29]:
datam.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [37]:
num_df = datam.select_dtypes(include='number')
num_df.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [41]:
non_num_df = datam.select_dtypes(include='object')
non_num_df.describe()

,country,description,designation,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,129908,129971,92506,129908,108724,50511,103727,98758,129971,129970,129971
unique,43,119955,37979,425,1229,17,19,15,118840,707,16757
top,US,This zesty red has pretty aromas that suggest ...,Reserve,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Wines & Winemakers
freq,54504,3,2009,36247,4480,11065,25514,25514,11,13272,222

In [49]:
datam[['country','title','price']]

         country                                              title  price
0          Italy                  Nicosia 2013 Vulkà Bianco  (Etna)    NaN
1       Portugal      Quinta dos Avidagos 2011 Avidagos Red (Douro)   15.0
2             US      Rainstorm 2013 Pinot Gris (Willamette Valley)   14.0
3             US  St. Julian 2013 Reserve Late Harvest Riesling ...   13.0
4             US  Sweet Cheeks 2012 Vintner's Reserve Wild Child...   65.0
...          ...                                                ...    ...
129966   Germany  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...   28.0
129967        US                  Citation 2004 Pinot Noir (Oregon)   75.0
129968    France  Domaine Gresser 2013 Kritt Gewurztraminer (Als...   30.0
129969    France      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)   32.0
129970    France  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...   21.0

[129971 rows x 3 columns]

In [53]:
datam['country'].values

array(['Italy', 'Portugal', 'US', ..., 'France', 'France', 'France'],
      dtype=object)

In [55]:
datam.index

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

In [57]:
datam.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [69]:
datam['country'].value_counts(ascending=True)

country
China                         1
Egypt                         1
Slovakia                      1
Armenia                       2
Bosnia and Herzegovina        2
Luxembourg                    6
Switzerland                   7
India                         9
Cyprus                       11
Czech Republic               12
Serbia                       12
Macedonia                    12
Ukraine                      14
Peru                         16
Morocco                      28
Lebanon                      35
Brazil                       52
Moldova                      59
Mexico                       70
Croatia                      73
England                      74
Georgia                      86
Slovenia                     87
Turkey                       90
Uruguay                     109
Romania                     120
Bulgaria                    141
Hungary                     146
Canada                      257
Greece                      466
Israel                      505
South Africa               1401
New Zealand                1419
Germany                    2165
Australia                  2329
Austria                    3345
Argentina                  3800
Chile                      4472
Portugal                   5691
Spain                      6645
Italy                     19540
France                    22093
US                        54504
Name: count, dtype: int64

In [71]:
datam['country'].value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedonia                    12
Czech Republic               12
Serbia                       12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [73]:
datam['points'].value_counts(ascending=True)

points
100       19
99        33
98        77
97       229
80       397
96       523
81       692
95      1535
82      1836
83      3025
94      3758
84      6480
93      6489
85      9530
92      9613
91     11359
89     12226
86     12600
90     15410
87     16933
88     17207
Name: count, dtype: int64

In [79]:
datar=datam.rename(columns={'country':'Country', 'points':'Points', 'description':'Description','designation':'Designation'
                     ,'price':'Price', 'province':'Province', 'region_1':'Region_2','region_1':'Region_2',
                     'taster_name': 'Taster_Name', 'taster_twitter_handle':'Taster_Twitter_Handle','title':'Title',
                     'variety':'Variety', 'winery':'Winery'})
datar

,Country,Description,Designation,Points,Price,Province,Region_2,region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [81]:
#datar.iloc[rows,columns]
datar.iloc[:1000,2:]

,Designation,Points,Price,Province,Region_2,region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...
995,Edèlmio,88,26.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Benanti 2006 Edèlmio White (Sicilia),White Blend,Benanti
996,Terre di Giumara,88,14.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Caruso & Minini 2006 Terre di Giumara Syrah (S...,Syrah,Caruso & Minini
997,Patchwork,88,18.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Yalumba 2006 Patchwork Shiraz (Barossa),Shiraz,Yalumba
998,NaN,88,18.0,Oregon,Dundee Hills,Willamette Valley,Paul Gregutt,@paulgwine,The Four Graces 2007 Pinot Gris (Dundee Hills),Pinot Gris,The Four Graces
999,NaN,88,17.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Amity 2006 Riesling (Willamette Valley),Riesling,Amity

In [83]:
datar.iloc[:1000,2::2]

,Designation,Price,Region_2,Taster_Name,Title,Winery
0,Vulkà Bianco,NaN,Etna,Kerin O’Keefe,Nicosia 2013 Vulkà Bianco (Etna),Nicosia
1,Avidagos,15.0,NaN,Roger Voss,Quinta dos Avidagos 2011 Avidagos Red (Douro),Quinta dos Avidagos
2,NaN,14.0,Willamette Valley,Paul Gregutt,Rainstorm 2013 Pinot Gris (Willamette Valley),Rainstorm
3,Reserve Late Harvest,13.0,Lake Michigan Shore,Alexander Peartree,St. Julian 2013 Reserve Late Harvest Riesling ...,St. Julian
4,Vintner's Reserve Wild Child Block,65.0,Willamette Valley,Paul Gregutt,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Sweet Cheeks
...,...,...,...,...,...,...
995,Edèlmio,26.0,Sicilia,NaN,Benanti 2006 Edèlmio White (Sicilia),Benanti
996,Terre di Giumara,14.0,Sicilia,NaN,Caruso & Minini 2006 Terre di Giumara Syrah (S...,Caruso & Minini
997,Patchwork,18.0,Barossa,Joe Czerwinski,Yalumba 2006 Patchwork Shiraz (Barossa),Yalumba
998,NaN,18.0,Dundee Hills,Paul Gregutt,The Four Graces 2007 Pinot Gris (Dundee Hills),The Four Graces
999,NaN,17.0,Willamette Valley,Paul Gregutt,Amity 2006 Riesling (Willamette Valley),Amity

In [103]:
datar.iloc[30000::-2,::2]          #iloc doesnot include last index

,Country,Designation,Price,Region_2,Taster_Name,Title,Winery
30000,Austria,Ried Grillenparz Reserve,40.0,NaN,Anne Krebiehl MW,Stadt Krems 2014 Ried Grillenparz Reserve Ries...,Stadt Krems
29998,US,High Elevation Collection,23.0,Lake County,Jim Gordon,Shannon Ridge 2013 High Elevation Collection P...,Shannon Ridge
29996,US,No. 198 Single Vineyard Reserve,19.0,Finger Lakes,Anna Lee C. Iijima,Boundary Breaks 2013 No. 198 Single Vineyard R...,Boundary Breaks
29994,France,Blue Label Brut,36.0,Champagne,Roger Voss,Nicolas Feuillatte NV Blue Label Brut (Champa...,Nicolas Feuillatte
29992,Greece,NaN,21.0,NaN,Susan Kostrzewa,Mediterra 2007 Vilana (Crete),Mediterra
...,...,...,...,...,...,...,...
8,Germany,Shine,12.0,NaN,Anna Lee C. Iijima,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Heinz Eifel
6,Italy,Belsito,16.0,Vittoria,Kerin O’Keefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Terre di Giurfo
4,US,Vintner's Reserve Wild Child Block,65.0,Willamette Valley,Paul Gregutt,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Sweet Cheeks
2,US,NaN,14.0,Willamette Valley,Paul Gregutt,Rainstorm 2013 Pinot Gris (Willamette Valley),Rainstorm
0,Italy,Vulkà Bianco,NaN,Etna,Kerin O’Keefe,Nicosia 2013 Vulkà Bianco (Etna),Nicosia

In [125]:
datar.isnull().sum(axis=0)

Country                     63
Description                  0
Designation              37465
Points                       0
Price                     8996
Province                    63
Region_2                 21247
region_2                 79460
Taster_Name              26244
Taster_Twitter_Handle    31213
Title                        0
Variety                      1
Winery                       0
dtype: int64

In [127]:
datar.isnull()

,Country,Description,Designation,Points,Price,Province,Region_2,region_2,Taster_Name,Taster_Twitter_Handle,Title,Variety,Winery
0,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,False,False,False,False,False,False,True,True,False,True,False,False,False
129967,False,False,True,False,False,False,False,False,False,False,False,False,False
129968,False,False,False,False,False,False,False,True,False,False,False,False,False
129969,False,False,True,False,False,False,False,True,False,False,False,False,False
129970,False,False,False,False,False,False,False,True,False,False,False,False,False