PANDAS CLASS 1

In [1]:
import pandas as pd

In [2]:
# A Pandas Series : continuous data, 1-D array holing data of any type, like a column in a table.

In [3]:
pd.__version__

'2.2.2'

In [4]:
fruits=['Apple', 'Banana', 'Orange', 'Cucumber']
pd.Series(fruits, index=[1,2,3,4])

1       Apple
2      Banana
3      Orange
4    Cucumber
dtype: object

In [5]:
num=[21,14,54,43]
pd.Series(num, index=[2,3,4,5])

2    21
3    14
4    54
5    43
dtype: int64

In [6]:
#list of even nos b2n 10 to 20, convert to series
L=[]
for i in range(10,21):
    L.append(i)
m=list(filter(lambda x: x%2==0,L))
pd.Series(m)

0    10
1    12
2    14
3    16
4    18
5    20
dtype: int64

In [7]:
l=[1,'A',-5,5.3,'Ram']
print(l)
pd.Series(l)

[1, 'A', -5, 5.3, 'Ram']

0      1
1      A
2     -5
3    5.3
4    Ram
dtype: object

CUSTOM INDEX

In [8]:
marks=[54,56,76,67]
sub=['English','Maths','Science','Art']
pd.Series(marks, index=sub)

English    54
Maths      56
Science    76
Art        67
dtype: int64

NAMING A SERIES

In [9]:
marks=[54,56,76,67]
sub=['English','Maths','Science','Art']
pd.Series(marks, index=sub, name='Marksheet')

English    54
Maths      56
Science    76
Art        67
Name: Marksheet, dtype: int64

In [10]:
num=[21,14,54,43]
pd.Series(num, index=['a','b','c','d'], name='Number', dtype=float)

a    21.0
b    14.0
c    54.0
d    43.0
Name: Number, dtype: float64

In [11]:
num=[2,2,2,2]
pd.Series(num, index=['a','b','c','d'], name='Number', dtype=float)

a    2.0
b    2.0
c    2.0
d    2.0
Name: Number, dtype: float64

In [12]:
s_scalar=pd.Series(2, index=['a','b','c','d'], name='Number', dtype=float)
s_scalar

a    2.0
b    2.0
c    2.0
d    2.0
Name: Number, dtype: float64

In [13]:
marks={'English':54, 'Maths':67, 'Science':87, 'Art':88}
marks_series=pd.Series(marks, name='Marksheet')
marks_series

English    54
Maths      67
Science    87
Art        88
Name: Marksheet, dtype: int64

Series attributes

In [14]:
marks_series.size

4

In [15]:
marks_series.dtype

dtype('int64')

In [16]:
marks_series.name

'Marksheet'

In [17]:
type(marks_series)

pandas.core.series.Series

In [18]:
marks_series.is_unique

True

In [19]:
pd.Series([1,2,3,1,2,3]).is_unique

False

In [20]:
marks_series.index

Index(['English', 'Maths', 'Science', 'Art'], dtype='object')

In [21]:
marks_series.values

array([54, 67, 87, 88], dtype=int64)

Series using read_csv()

In [22]:
pd.read_csv('internet.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [47]:
ipl=pd.read_csv('kohli_ipl.csv', index_col='match_no')
#ipl=pd.read_csv('kohli_ipl.csv')
ipl
#type(ipl)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [24]:
ipl.head()  #default=5

          runs
match_no
1            1
2           23
3           13
4           12
5            1

In [25]:
ipl.sample()   #randomly chosen one

          runs
match_no
84          14

In [26]:
ipl.sample(5)

          runs
match_no
195          4
30          38
28          17
55           8
10           3

In [27]:
ipl.tail()    #default=5

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [28]:
mov=pd.read_csv('bollywood.csv', index_col='movie')
mov.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Kashmira Shah        1
Kartik Elangovan     1
Karisma Kapoor       1
Karan Sharma         1
Zulfi Sayed          1
Name: count, Length: 566, dtype: int64

In [29]:
#inplace sort_values
ipl.sort_values('match_no', ascending=False).head(1).values[0]

array([7], dtype=int64)

In [30]:
ipl.sort_index().head(1).values[0]

array([1], dtype=int64)

In [31]:
ipl.sort_values('match_no', inplace=True)
ipl

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [32]:
ipl.count()

runs    215
dtype: int64

In [33]:
l=pd.Series([1,2,3,4,5,7,7,8,9,10])
l

0     1
1     2
2     3
3     4
4     5
5     7
6     7
7     8
8     9
9    10
dtype: int64

In [34]:
print(l.sum())

56

In [49]:
import numpy as np
l.mean()
np.mean(l)
print(l.mean())

5.6

In [36]:
print(l.median())

6.0

In [37]:
print(l.mode())

0    7
dtype: int64

In [38]:
print(l.std())

3.0623157540948935

In [39]:
print(l.var())

9.377777777777776

In [40]:
print(l.describe())

count    10.000000
mean      5.600000
std       3.062316
min       1.000000
25%       3.250000
50%       6.000000
75%       7.750000
max      10.000000
dtype: float64

In [41]:
print(l.max())

10

In [42]:
print(l.min())

1

In [43]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,0])
a=s1+s2
print(a)

0     7
1     9
2    11
3    13
4     5
dtype: int64

In [44]:
s1+4*s2

0    25
1    30
2    35
3    40
4     5
dtype: int64

In [45]:
s1.add(s2)

0     7
1     9
2    11
3    13
4     5
dtype: int64